debug: false           # debug logging
timeout: 2             # http requests timeout
ndigits: 3             # digits after floating point or after zeroes
coinapi_keys:
  - key
  - key2               # coinapi keys list
telegram_token:        # telegram bot token
