services:
  shirino:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './config.yaml:/config.yaml'
      - 'shirino-db:/data'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./CertSSL:/etc/nginx/ssl

volumes:
  shirino:
    driver: local
  shirino-db: